In [32]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split

In [33]:
np.random.seed(42)
n= 10000

df = pd.DataFrame({
    "Age" : np.random.randint(17,26,n),
    "Gender": np.random.choice(["Male","Female"],n),
    "Attendance":np.random.randint(40,101,n),
    "CGPA":np.round(np.random.uniform(4.5,10,n),2),
    "Backlogs":np.random.randint(0,8,n),
    "FamilyIncome":np.random.randint(150000,1200000,n),
    "StudyHour":np.round(np.random.uniform(0.5,8,n),1),
    "Scholarship":np.random.choice([0,1],n,p=[0.7,0.3]),
    "InternetAccess":np.random.choice([0,1],n,p=[0.15,0.85]),
    "Hostel":np.random.choice([0,1],n),
    "MentalStress":np.random.randint(1,11,n),
    "Partimejob":np.random.choice([0,1],n,p=[0.75,0.25])
}
)

In [34]:
#Low attendance
risk = (
    (df["Attendance"] <65).astype(int)+
    (df["CGPA"] <6.0).astype(int)+
    (df["Backlogs"] >=3).astype(int)+
    (df["MentalStress"] >=8).astype(int)+
    (df["StudyHour"] <2).astype(int)
)
df["Dropout"] = np.where(risk>=3,1,0)

In [35]:
df

,Age,Gender,Attendance,CGPA,Backlogs,FamilyIncome,StudyHour,Scholarship,InternetAccess,Hostel,MentalStress,Partimejob,Dropout
0,23,Female,70,5.71,3,647769,5.7,0,1,0,7,0,0
1,20,Female,45,6.17,6,403202,6.9,1,1,0,9,0,1
2,24,Male,53,5.21,7,777807,0.6,0,1,0,4,0,1
3,21,Female,97,5.87,0,646632,2.5,0,0,0,6,0,0
4,23,Male,62,9.02,2,425485,4.6,0,1,0,9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,Female,70,4.77,6,768810,3.7,0,1,1,9,1,1
9996,23,Male,48,7.05,5,315999,0.9,1,0,1,3,1,1
9997,22,Male,61,9.10,0,628320,2.5,1,1,1,5,0,0
9998,25,Female,50,5.49,5,600933,2.4,1,1,0,7,0,1
9999,23,Female,56,5.30,5,764767,2.1,1,0,0,1,0,1

In [36]:
X =df.drop("Dropout",axis=1)
y=df["Dropout"]

In [37]:
X

,Age,Gender,Attendance,CGPA,Backlogs,FamilyIncome,StudyHour,Scholarship,InternetAccess,Hostel,MentalStress,Partimejob
0,23,Female,70,5.71,3,647769,5.7,0,1,0,7,0
1,20,Female,45,6.17,6,403202,6.9,1,1,0,9,0
2,24,Male,53,5.21,7,777807,0.6,0,1,0,4,0
3,21,Female,97,5.87,0,646632,2.5,0,0,0,6,0
4,23,Male,62,9.02,2,425485,4.6,0,1,0,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,Female,70,4.77,6,768810,3.7,0,1,1,9,1
9996,23,Male,48,7.05,5,315999,0.9,1,0,1,3,1
9997,22,Male,61,9.10,0,628320,2.5,1,1,1,5,0
9998,25,Female,50,5.49,5,600933,2.4,1,1,0,7,0
9999,23,Female,56,5.30,5,764767,2.1,1,0,0,1,0

In [38]:
X = pd.get_dummies(X,drop_first=True)

In [39]:
X

,Age,Attendance,CGPA,Backlogs,FamilyIncome,StudyHour,Scholarship,InternetAccess,Hostel,MentalStress,Partimejob,Gender_Male
0,23,70,5.71,3,647769,5.7,0,1,0,7,0,False
1,20,45,6.17,6,403202,6.9,1,1,0,9,0,False
2,24,53,5.21,7,777807,0.6,0,1,0,4,0,True
3,21,97,5.87,0,646632,2.5,0,0,0,6,0,False
4,23,62,9.02,2,425485,4.6,0,1,0,9,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,70,4.77,6,768810,3.7,0,1,1,9,1,False
9996,23,48,7.05,5,315999,0.9,1,0,1,3,1,True
9997,22,61,9.10,0,628320,2.5,1,1,1,5,0,True
9998,25,50,5.49,5,600933,2.4,1,1,0,7,0,False
9999,23,56,5.30,5,764767,2.1,1,0,0,1,0,False

In [40]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 41,
    stratify =y
)

In [42]:
X_train.shape

(8000, 12)

In [43]:
X_test.shape

(2000, 12)

In [44]:
y_test.shape

(2000,)

In [45]:
y_train.shape

(8000,)

In [47]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\parve\downloads\anaconda\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\parve\downloads\anaconda\lib\site-packages (from xgboost) (1.16.3)
Using cached xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0
Note: you may need to restart the kernel to use updated packages.

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

In [50]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN":KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "XGBoost": XGBClassifier(),
    "Naive Bayes": GaussianNB()  
}

In [51]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict class labels
    y_pred = model.predict(X_test)

    # Predict probabilities
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        # SVM without probability=True
        y_prob = y_pred

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC AUC": roc_auc_score(y_test, y_prob)
    })

C:\Users\parve\Downloads\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\parve\Downloads\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\parve\Downloads\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [52]:
result_df = pd.DataFrame(results)
result_df = result_df.sort_values(
    by="Accuracy",
    ascending = False
)
result_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
3        Random Forest    0.9995   1.000000  0.997881  0.998940  1.000000
5              XGBoost    0.9995   1.000000  0.997881  0.998940  0.999999
2        Decision Tree    0.9990   0.997881  0.997881  0.997881  0.998613
0  Logistic Regression    0.8600   0.759459  0.595339  0.667458  0.919921
4                  SVM    0.7640   0.000000  0.000000  0.000000  0.500000
6          Naive Bayes    0.7640   0.000000  0.000000  0.000000  0.755414
1                  KNN    0.7080   0.225490  0.097458  0.136095  0.501159